HUBOT_WORMHOLE_IN=$HUBOT_WORMHOLE_IN \
HUBOT_WORMHOLE_OUT=$HUBOT_WORMHOLE_OUT \
HUBOT_GCP_PROJECT_ID=$HUBOT_GCP_PROJECT_ID \
GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS \
HUBOT_WORMHOLE_TOPIC_NAME=$HUBOT_WORMHOLE_TOPIC_NAME \
HUBOT_WORMHOLE_SUBSCRIPTION_NAMES=$HUBOT_WORMHOLE_SUBSCRIPTION_NAMES \
HUBOT_WORMHOLE_ALLOW_CHANNELS=$HUBOT_WORMHOLE_ALLOW_CHANNELS \
HUBOT_SLACK_TOKEN=$HUBOT_SLACK_TOKEN \
./bin/hubot --adapter slack --disable-httpd
